# Generated by Django 5.1.7 on 2025-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=500)),
                ('printify_id', models.CharField(max_length=100, unique=True)),
                ('sizes', models.JSONField()),
            ],
        ),
    ]
