# Generated by Django 5.2.1 on 2025-05-10 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WinningCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The 6-digit winning code.', max_length=6, unique=True)),
                ('prize_description', models.CharField(help_text='Description of the prize for this code.', max_length=255)),
                ('is_claimed', models.BooleanField(default=False, help_text='Has this prize been claimed?')),
                ('claimed_by_identifier', models.CharField(blank=True, help_text='Identifier of the winner (e.g., email or a session key if anonymous).', max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When this prize was claimed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Winning Code',
                'verbose_name_plural': 'Winning Codes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('variant_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text="User's session key for anonymous tracking.", max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('submitted_code', models.CharField(help_text='The code submitted by the user.', max_length=6)),
                ('is_winner', models.BooleanField(default=False, help_text='Was this attempt a winning one?')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('winning_code_matched', models.ForeignKey(blank=True, help_text='Which winning code was matched, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.winningcode')),
            ],
            options={
                'verbose_name': 'Competition Attempt',
                'verbose_name_plural': 'Competition Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
