# Generated by Django 5.2.1 on 2025-05-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='printify_variant_id',
            field=models.CharField(blank=True, help_text='Printify variant ID of the purchased item.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The base product ordered.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='mockup_image',
            field=models.ImageField(blank=True, help_text='Base image for the product customizer (e.g., blank T-shirt, mug).', null=True, upload_to='product_mockups/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(help_text='Redundant but useful for displaying name if product is deleted.', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_title',
            field=models.CharField(blank=True, help_text="e.g., 'Large, Black' for a T-shirt.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_blueprint_id',
            field=models.IntegerField(blank=True, help_text='Printify Blueprint ID for this product type.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_id',
            field=models.CharField(db_index=True, help_text='Unique Product ID from Printify. This is for synced products.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_print_provider_id',
            field=models.IntegerField(blank=True, help_text='Printify Print Provider ID associated with this product.', null=True),
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_image', models.ImageField(help_text='Rendered PNG image of the custom design.', upload_to='custom_designs/%Y/%m/%d/')),
                ('design_json', models.JSONField(blank=True, help_text='Fabric.js JSON representation of the design for future editing.', null=True)),
                ('selected_product_type', models.CharField(help_text='e.g., T-Shirt, Hoodie, Mug - from frontend selection.', max_length=100)),
                ('selected_size', models.CharField(help_text='e.g., S, M, L, XL - from frontend selection.', max_length=50)),
                ('selected_color', models.CharField(help_text='e.g., White, Black, Navy - from frontend selection.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printify_image_id', models.CharField(blank=True, help_text='Printify asset ID for the uploaded design image.', max_length=100, null=True)),
                ('printify_product_id', models.CharField(blank=True, help_text='Printify product ID if a unique product was created for this design.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('uploaded_to_printify', 'Image Uploaded to Printify'), ('printify_product_ready', 'Printify Product Ready (Draft)'), ('added_to_cart', 'Added to User Cart'), ('order_created', 'Order Created on Printify'), ('fulfilled', 'Fulfilled by Printify'), ('failed', 'Failed to Process')], default='pending', help_text='Current processing status of the custom design.', max_length=50)),
                ('product', models.ForeignKey(help_text='The base product type this design is for (e.g., T-Shirt, Hoodie).', on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who created the design (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Design',
                'verbose_name_plural': 'Custom Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_design',
            field=models.OneToOneField(blank=True, help_text='If this is a customized product, link to its design.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customdesign'),
        ),
    ]
