# Generated by Django 5.2.1 on 2025-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_winningcode_product_created_at_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('SITE_LAUNCH', 'Site Launch Date/Time')], help_text='The unique name of the event (e.g., Site Launch Date/Time).', max_length=50, unique=True)),
                ('event_datetime', models.DateTimeField(help_text='The date and time of the event.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this event currently active/relevant for display (e.g., for a countdown)?')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Event',
                'verbose_name_plural': 'Site Events',
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Synced Product', 'verbose_name_plural': 'Synced Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price_ngn',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base display price in NGN.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is the product published on Printify?'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last sync from Printify.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image_url',
            field=models.URLField(blank=True, help_text='URL of the primary display image.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_blueprint_id',
            field=models.IntegerField(blank=True, help_text='Printify Blueprint ID.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_print_provider_id',
            field=models.IntegerField(blank=True, help_text='Printify Print Provider ID.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_shop_id',
            field=models.CharField(blank=True, db_index=True, help_text='Printify Shop ID this product belongs to.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_options_data',
            field=models.JSONField(blank=True, default=list, help_text='Structured product options (e.g., Color, Size) from Printify.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags associated with the product from Printify.'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants_data',
            field=models.JSONField(blank=True, default=list, help_text='Detailed list of all product variants with their properties.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='printify_id',
            field=models.CharField(db_index=True, help_text='Unique Product ID from Printify.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='winningcode',
            name='claimed_by_identifier',
            field=models.CharField(blank=True, help_text='Identifier of the winner (e.g., email or session key).', max_length=255, null=True),
        ),
    ]
