# Generated by Django 5.2.1 on 2025-05-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_siteevent_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who placed the order, if authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='event_name',
            field=models.CharField(choices=[('SITE_LAUNCH', 'Site Launch Date/Time')], help_text='The unique name of the event.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this event currently active/relevant?'),
        ),
    ]
