# Generated by Django 5.2.1 on 2025-05-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_user_alter_siteevent_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price_ngn',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base display price in NGN (e.g., price of the default or first available variant).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_options_data',
            field=models.JSONField(blank=True, default=list, help_text='Structured product options (e.g., Color, Size) from Printify, including option value IDs.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants_data',
            field=models.JSONField(blank=True, default=list, help_text='Detailed list of all product variants with their properties, prices, and defining option value IDs.'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='event_name',
            field=models.CharField(choices=[('SITE_LAUNCH', 'Site Launch Date/Time')], help_text='The unique name of the event (e.g., Site Launch Date/Time).', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this event currently active/relevant for display (e.g., for a countdown)?'),
        ),
    ]
